import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
      {/* <img src="/img/WelcomeIMG.jpg" alt="" /> */}
      <Image src='/img/WelcomeIMG.jpg' height={200} width ={150} />
        <h1 className={styles.title}>
        
        </h1>
      </main>

    </div>
  )
}
